# ***covid 19 project***

# **Creating dataset**

In [16]:
import pandas as pd
import numpy as np

covid_data = {
    'Country': ['India','USA','Brazil','UK','France','Germany','Japan','China','Russia','Canada',
                'Italy','Spain','Australia','Mexico','South Korea','India','USA','Brazil','UK','France'],

    'Cases': [45000,np.nan,32000,15000,18000,np.nan,9000,5000,12000,7000,
              np.nan,11000,3000,8000,6000,47000,52000,np.nan,17000,19000],

    'Deaths': [500,800,np.nan,200,250,180,np.nan,50,170,90,
               220,np.nan,30,120,60,510,820,410,np.nan,260],

    'Vaccinated': [80,75,np.nan,85,82,88,90,np.nan,70,89,
                   84,81,np.nan,76,92,83,77,74,86,np.nan]
}

df = pd.DataFrame(covid_data)

display(df)

        Country    Cases  Deaths  Vaccinated
0         India  45000.0   500.0        80.0
1           USA      NaN   800.0        75.0
2        Brazil  32000.0     NaN         NaN
3            UK  15000.0   200.0        85.0
4        France  18000.0   250.0        82.0
5       Germany      NaN   180.0        88.0
6         Japan   9000.0     NaN        90.0
7         China   5000.0    50.0         NaN
8        Russia  12000.0   170.0        70.0
9        Canada   7000.0    90.0        89.0
10        Italy      NaN   220.0        84.0
11        Spain  11000.0     NaN        81.0
12    Australia   3000.0    30.0         NaN
13       Mexico   8000.0   120.0        76.0
14  South Korea   6000.0    60.0        92.0
15        India  47000.0   510.0        83.0
16          USA  52000.0   820.0        77.0
17       Brazil      NaN   410.0        74.0
18           UK  17000.0     NaN        86.0
19       France  19000.0   260.0         NaN

In [17]:
df.to_csv("covid_messy_dataset.csv", index=False)

print("Dataset Saved Successfully")

Dataset Saved Successfully

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Country     20 non-null     object
 1   Cases       16 non-null     float64
 2   Deaths      16 non-null     float64
 3   Vaccinated  16 non-null     float64
dtypes: float64(3), object(1)
memory usage: 772.0+ bytes

In [19]:
df.isnull().sum()

Country       0
Cases         4
Deaths        4
Vaccinated    4
dtype: int64

In [20]:
total_missing = df.isnull().sum().sum()
print("Total Missing Values:", total_missing)

Total Missing Values: 12

## **Manual Cleaning**

In [21]:
import pandas as pd

# Load dataset
df = pd.read_csv("//content/covid_messy_dataset.csv")

# Check missing values before cleaning
print("Missing values before cleaning:")
print(df.isnull().sum())

# Remove all rows containing at least one missing value
df_manual = df.dropna()

# Check missing values after cleaning
print("\nMissing values after cleaning:")
print(df_manual.isnull().sum())

# Compare dataset size
print("\nOriginal Shape:", df.shape)
print("Cleaned Shape:", df_manual.shape)

# Save cleaned dataset
df_manual.to_csv("covid_manual_cleaned.csv", index=False)

print("\nCleaned dataset saved successfully!")

Missing values before cleaning:
Country       0
Cases         4
Deaths        4
Vaccinated    4
dtype: int64

Missing values after cleaning:
Country       0
Cases         0
Deaths        0
Vaccinated    0
dtype: int64

Original Shape: (20, 4)
Cleaned Shape: (9, 4)

Cleaned dataset saved successfully!

In [23]:
# Check total missing values
print(df.isnull().sum().sum())

# Remove all rows containing any NaN
df_manual = df.dropna(how='any')

# Reset index
df_manual = df_manual.reset_index(drop=True)

# Show cleaned data
display(df_manual.head(10))

12

       Country    Cases  Deaths  Vaccinated
0        India  45000.0   500.0        80.0
1           UK  15000.0   200.0        85.0
2       France  18000.0   250.0        82.0
3       Russia  12000.0   170.0        70.0
4       Canada   7000.0    90.0        89.0
5       Mexico   8000.0   120.0        76.0
6  South Korea   6000.0    60.0        92.0
7        India  47000.0   510.0        83.0
8          USA  52000.0   820.0        77.0

# mean cleaning

In [29]:
df_mean = df.copy()

df_mean['Cases'] = df_mean['Cases'].fillna(df_mean['Cases'].mean())
df_mean['Deaths'] = df_mean['Deaths'].fillna(df_mean['Deaths'].mean())
df_mean['Vaccinated'] = df_mean['Vaccinated'].fillna(df_mean['Vaccinated'].mean())

display(df_mean)

        Country    Cases   Deaths  Vaccinated
0         India  45000.0  500.000        80.0
1           USA  19125.0  800.000        75.0
2        Brazil  32000.0  291.875        82.0
3            UK  15000.0  200.000        85.0
4        France  18000.0  250.000        82.0
5       Germany  19125.0  180.000        88.0
6         Japan   9000.0  291.875        90.0
7         China   5000.0   50.000        82.0
8        Russia  12000.0  170.000        70.0
9        Canada   7000.0   90.000        89.0
10        Italy  19125.0  220.000        84.0
11        Spain  11000.0  291.875        81.0
12    Australia   3000.0   30.000        82.0
13       Mexico   8000.0  120.000        76.0
14  South Korea   6000.0   60.000        92.0
15        India  47000.0  510.000        83.0
16          USA  52000.0  820.000        77.0
17       Brazil  19125.0  410.000        74.0
18           UK  17000.0  291.875        86.0
19       France  19000.0  260.000        82.0

## **mode cleaning**

In [30]:
df_mode = df.copy()

df_mode['Cases'] = df_mode['Cases'].fillna(df_mode['Cases'].mode()[0])
df_mode['Deaths'] = df_mode['Deaths'].fillna(df_mode['Deaths'].mode()[0])
df_mode['Vaccinated'] = df_mode['Vaccinated'].fillna(df_mode['Vaccinated'].mode()[0])

display(df_mode)

        Country    Cases  Deaths  Vaccinated
0         India  45000.0   500.0        80.0
1           USA   3000.0   800.0        75.0
2        Brazil  32000.0    30.0        70.0
3            UK  15000.0   200.0        85.0
4        France  18000.0   250.0        82.0
5       Germany   3000.0   180.0        88.0
6         Japan   9000.0    30.0        90.0
7         China   5000.0    50.0        70.0
8        Russia  12000.0   170.0        70.0
9        Canada   7000.0    90.0        89.0
10        Italy   3000.0   220.0        84.0
11        Spain  11000.0    30.0        81.0
12    Australia   3000.0    30.0        70.0
13       Mexico   8000.0   120.0        76.0
14  South Korea   6000.0    60.0        92.0
15        India  47000.0   510.0        83.0
16          USA  52000.0   820.0        77.0
17       Brazil   3000.0   410.0        74.0
18           UK  17000.0    30.0        86.0
19       France  19000.0   260.0        70.0

## **median cleaning**

In [31]:
df_median = df.copy()

df_median['Cases'] = df_median['Cases'].fillna(df_median['Cases'].median())
df_median['Deaths'] = df_median['Deaths'].fillna(df_median['Deaths'].median())
df_median['Vaccinated'] = df_median['Vaccinated'].fillna(df_median['Vaccinated'].median())

display(df_median)

        Country    Cases  Deaths  Vaccinated
0         India  45000.0   500.0        80.0
1           USA  13500.0   800.0        75.0
2        Brazil  32000.0   210.0        82.5
3            UK  15000.0   200.0        85.0
4        France  18000.0   250.0        82.0
5       Germany  13500.0   180.0        88.0
6         Japan   9000.0   210.0        90.0
7         China   5000.0    50.0        82.5
8        Russia  12000.0   170.0        70.0
9        Canada   7000.0    90.0        89.0
10        Italy  13500.0   220.0        84.0
11        Spain  11000.0   210.0        81.0
12    Australia   3000.0    30.0        82.5
13       Mexico   8000.0   120.0        76.0
14  South Korea   6000.0    60.0        92.0
15        India  47000.0   510.0        83.0
16          USA  52000.0   820.0        77.0
17       Brazil  13500.0   410.0        74.0
18           UK  17000.0   210.0        86.0
19       France  19000.0   260.0        82.5

## comparison

In [32]:
print("Original Missing Values")
print(df.isnull().sum())

print("\nManual Cleaning")
print(df_manual.isnull().sum())

print("\nMean Cleaning")
print(df_mean.isnull().sum())

print("\nMedian Cleaning")
print(df_median.isnull().sum())

print("\nMode Cleaning")
print(df_mode.isnull().sum())

Original Missing Values
Country       0
Cases         4
Deaths        4
Vaccinated    4
dtype: int64

Manual Cleaning
Country       0
Cases         0
Deaths        0
Vaccinated    0
dtype: int64

Mean Cleaning
Country       0
Cases         0
Deaths        0
Vaccinated    0
dtype: int64

Median Cleaning
Country       0
Cases         0
Deaths        0
Vaccinated    0
dtype: int64

Mode Cleaning
Country       0
Cases         0
Deaths        0
Vaccinated    0
dtype: int64

In [33]:
df_manual.to_csv("covid_manual_cleaned.csv", index=False)

# **Automatic Cleaning**

In [25]:
df_auto = df.copy()

df_auto['Cases'].fillna(df_auto['Cases'].mean(), inplace=True)

df_auto['Deaths'].fillna(df_auto['Deaths'].mean(), inplace=True)

df_auto['Vaccinated'].fillna(df_auto['Vaccinated'].mean(), inplace=True)

display(df_auto)

/tmp/ipykernel_7533/709498286.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_auto['Cases'].fillna(df_auto['Cases'].mean(), inplace=True)
/tmp/ipykernel_7533/709498286.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_auto['Deaths'].fillna(df_auto['Deaths'].mean(), inplace=True)
/tmp/ipykernel_7533/709498286.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_auto['Vaccinated'].fillna(df_auto['Vaccinated'].mean(), inplace=True)

        Country    Cases   Deaths  Vaccinated
0         India  45000.0  500.000        80.0
1           USA  19125.0  800.000        75.0
2        Brazil  32000.0  291.875        82.0
3            UK  15000.0  200.000        85.0
4        France  18000.0  250.000        82.0
5       Germany  19125.0  180.000        88.0
6         Japan   9000.0  291.875        90.0
7         China   5000.0   50.000        82.0
8        Russia  12000.0  170.000        70.0
9        Canada   7000.0   90.000        89.0
10        Italy  19125.0  220.000        84.0
11        Spain  11000.0  291.875        81.0
12    Australia   3000.0   30.000        82.0
13       Mexico   8000.0  120.000        76.0
14  South Korea   6000.0   60.000        92.0
15        India  47000.0  510.000        83.0
16          USA  52000.0  820.000        77.0
17       Brazil  19125.0  410.000        74.0
18           UK  17000.0  291.875        86.0
19       France  19000.0  260.000        82.0

In [26]:
df_auto.isnull().sum()

Country       0
Cases         0
Deaths        0
Vaccinated    0
dtype: int64

# **mean**

In [34]:
df_mean = df.copy()

df_mean['Cases'] = df_mean['Cases'].fillna(df_mean['Cases'].mean())
df_mean['Deaths'] = df_mean['Deaths'].fillna(df_mean['Deaths'].mean())
df_mean['Vaccinated'] = df_mean['Vaccinated'].fillna(df_mean['Vaccinated'].mean())

display(df_mean)

        Country    Cases   Deaths  Vaccinated
0         India  45000.0  500.000        80.0
1           USA  19125.0  800.000        75.0
2        Brazil  32000.0  291.875        82.0
3            UK  15000.0  200.000        85.0
4        France  18000.0  250.000        82.0
5       Germany  19125.0  180.000        88.0
6         Japan   9000.0  291.875        90.0
7         China   5000.0   50.000        82.0
8        Russia  12000.0  170.000        70.0
9        Canada   7000.0   90.000        89.0
10        Italy  19125.0  220.000        84.0
11        Spain  11000.0  291.875        81.0
12    Australia   3000.0   30.000        82.0
13       Mexico   8000.0  120.000        76.0
14  South Korea   6000.0   60.000        92.0
15        India  47000.0  510.000        83.0
16          USA  52000.0  820.000        77.0
17       Brazil  19125.0  410.000        74.0
18           UK  17000.0  291.875        86.0
19       France  19000.0  260.000        82.0

# median

In [35]:
df_median = df.copy()

df_median['Cases'] = df_median['Cases'].fillna(df_median['Cases'].median())
df_median['Deaths'] = df_median['Deaths'].fillna(df_median['Deaths'].median())
df_median['Vaccinated'] = df_median['Vaccinated'].fillna(df_median['Vaccinated'].median())

display(df_median)

        Country    Cases  Deaths  Vaccinated
0         India  45000.0   500.0        80.0
1           USA  13500.0   800.0        75.0
2        Brazil  32000.0   210.0        82.5
3            UK  15000.0   200.0        85.0
4        France  18000.0   250.0        82.0
5       Germany  13500.0   180.0        88.0
6         Japan   9000.0   210.0        90.0
7         China   5000.0    50.0        82.5
8        Russia  12000.0   170.0        70.0
9        Canada   7000.0    90.0        89.0
10        Italy  13500.0   220.0        84.0
11        Spain  11000.0   210.0        81.0
12    Australia   3000.0    30.0        82.5
13       Mexico   8000.0   120.0        76.0
14  South Korea   6000.0    60.0        92.0
15        India  47000.0   510.0        83.0
16          USA  52000.0   820.0        77.0
17       Brazil  13500.0   410.0        74.0
18           UK  17000.0   210.0        86.0
19       France  19000.0   260.0        82.5

In [37]:
print("Original Missing Values")
print(df.isnull().sum())

print("\nManual Cleaning")
print(df_manual.isnull().sum())

print("\nMean Cleaning")
print(df_mean.isnull().sum())

print("\nMedian Cleaning")
print(df_median.isnull().sum())

print("\nMode Cleaning")
print(df_mode.isnull().sum())

Original Missing Values
Country       0
Cases         4
Deaths        4
Vaccinated    4
dtype: int64

Manual Cleaning
Country       0
Cases         0
Deaths        0
Vaccinated    0
dtype: int64

Mean Cleaning
Country       0
Cases         0
Deaths        0
Vaccinated    0
dtype: int64

Median Cleaning
Country       0
Cases         0
Deaths        0
Vaccinated    0
dtype: int64

Mode Cleaning
Country       0
Cases         0
Deaths        0
Vaccinated    0
dtype: int64

In [27]:
df_auto.to_csv("covid_auto_cleaned.csv", index=False)

In [36]:
from google.colab import files

files.download("covid_manual_cleaned.csv")
files.download("covid_auto_cleaned.csv")

# **Questions**

highest covid cases

In [38]:
df.loc[df['Cases'].idxmax()]

Country           USA
Cases         52000.0
Deaths          820.0
Vaccinated       77.0
Name: 16, dtype: object

lowest covid cases

In [39]:
df.loc[df['Cases'].idxmin()]

Country       Australia
Cases            3000.0
Deaths             30.0
Vaccinated          NaN
Name: 12, dtype: object

average no of covid cases across all countries

In [40]:
df['Cases'].mean()

np.float64(19125.0)

country with highest vaccinated

In [41]:
df.loc[df['Vaccinated'].idxmax()]

Country       South Korea
Cases              6000.0
Deaths               60.0
Vaccinated           92.0
Name: 14, dtype: object

total covid cases

In [42]:
df['Cases'].sum()

np.float64(306000.0)